title: National Elections Database
description: A website for hosting the National Elections Database with the aim of facilitating future electoral research.
theme: jekyll-theme-minimal
baseurl: "" # Leave empty unless your site is hosted in a subfolder
url: https://<Jade-Sillere>.github.io # Replace with your GitHub Pages URL